blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/A7Lavinraj/fyler.nvim/discussions
    about: Usage questions and support requests are answered in the discussions
