name: CI
on:
  - push
  - pull_request
jobs:
  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color always --check lua/ tests/
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: selene
      - name: run linters
        run: make lint
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: folke/github/neovim@main
      - name: Installing dependencies
        run: |
          git config --global core.compression 0
          git clone https://github.com/nvim-mini/mini.test .tests/repos/mini.test
      - name: Running tests
        run: make test
